package com.dracarys.idr

import com.dracarys.idr.calibration.DeviceOrientationCalibrator
import com.dracarys.idr.fusion.ESKFFusion
import org.junit.Assert.assertEquals
import org.junit.BeforeClass
import org.junit.Test
import java.io.InputStreamReader

/**
 * Numerical Cross-Check Test:
 * Verifies Kotlin implementations of [DeviceOrientationCalibrator] and [ESKFFusion]
 * against the real IO-VNBD drive S1 reference outputs generated by Python.
 *
 * Asserts floating-point equality across:
 * - Gravity unit Up vector u_up
 * - Project vehicle yaw rate
 * - Leveled & rotated body accelerations af, al
 * - ESKF state trajectory x, y, vf, vl, psi, and gyro bias
 */
class NumericalCrossCheckTest {

    companion object {
        private lateinit var jsonString: String

        @BeforeClass
        @JvmStatic
        fun loadVectors() {
            val stream = NumericalCrossCheckTest::class.java.classLoader
                ?.getResourceAsStream("real_segment_test_vectors.json")
                ?: error("Could not find real_segment_test_vectors.json resource")
            jsonString = InputStreamReader(stream, Charsets.UTF_8).readText()
        }

        private fun extractDoubleArray(json: String, key: String): DoubleArray {
            val pattern = """"$key":\s*\[([^\]]*)\]""".toRegex()
            val match = pattern.find(json) ?: error("Key $key not found in test vectors")
            val raw = match.groupValues[1].trim()
            if (raw.isEmpty()) return doubleArrayOf()
            return raw.split(",").map { it.trim().toDouble() }.toDoubleArray()
        }

        private fun extractIntArray(json: String, key: String): IntArray {
            val pattern = """"$key":\s*\[([^\]]*)\]""".toRegex()
            val match = pattern.find(json) ?: error("Key $key not found in test vectors")
            val raw = match.groupValues[1].trim()
            if (raw.isEmpty()) return intArrayOf()
            return raw.split(",").map { it.trim().toInt() }.toIntArray()
        }

        private fun extractBooleanArray(json: String, key: String): BooleanArray {
            val pattern = """"$key":\s*\[([^\]]*)\]""".toRegex()
            val match = pattern.find(json) ?: error("Key $key not found in test vectors")
            val raw = match.groupValues[1].trim()
            if (raw.isEmpty()) return booleanArrayOf()
            return raw.split(",").map { it.trim().toBoolean() }.toBooleanArray()
        }

        private fun extractDouble(json: String, key: String): Double {
            val pattern = """"$key":\s*([0-9.eE+-]+)""".toRegex()
            val match = pattern.find(json) ?: error("Key $key not found in test vectors")
            return match.groupValues[1].toDouble()
        }

        private fun extractNestedDoubleArray(json: String, key: String): List<DoubleArray> {
            val pattern = """"$key":\s*\[\s*(\[[^\]]*\](?:\s*,\s*\[[^\]]*\])*)\s*\]""".toRegex()
            val match = pattern.find(json) ?: return emptyList()
            val innerPattern = """\[([^\]]*)\]""".toRegex()
            return innerPattern.findAll(match.groupValues[1]).map { m ->
                val inner = m.groupValues[1].trim()
                if (inner.isEmpty()) doubleArrayOf()
                else inner.split(",").map { it.trim().toDouble() }.toDoubleArray()
            }.toList()
        }
    }

    @Test
    fun `numerical cross check calibration against python reference on real IO-VNBD segment`() {
        val t = extractDoubleArray(jsonString, "t")
        val gx = extractDoubleArray(jsonString, "gx")
        val gy = extractDoubleArray(jsonString, "gy")
        val gz = extractDoubleArray(jsonString, "gz")
        val ax = extractDoubleArray(jsonString, "ax")
        val ay = extractDoubleArray(jsonString, "ay")
        val az = extractDoubleArray(jsonString, "az")
        val gravX = extractDoubleArray(jsonString, "grav_x")
        val gravY = extractDoubleArray(jsonString, "grav_y")
        val gravZ = extractDoubleArray(jsonString, "grav_z")

        val refUUp = extractNestedDoubleArray(jsonString, "u_up")
        val refYawRate = extractDoubleArray(jsonString, "yaw_rate")
        val refAfProj = extractDoubleArray(jsonString, "af_proj")
        val refAlProj = extractDoubleArray(jsonString, "al_proj")

        val calibrator = DeviceOrientationCalibrator()

        val n = t.size
        for (k in 0 until n) {
            val gK = doubleArrayOf(gravX[k], gravY[k], gravZ[k])
            val gyroK = doubleArrayOf(gx[k], gy[k], gz[k])
            val accK = doubleArrayOf(ax[k], ay[k], az[k])

            val uUp = DeviceOrientationCalibrator.computeGravityUnitUp(gK)
            if (refUUp.isNotEmpty()) {
                assertEquals("u_up[0] mismatch at step $k", refUUp[k][0], uUp[0], 1e-5)
                assertEquals("u_up[1] mismatch at step $k", refUUp[k][1], uUp[1], 1e-5)
                assertEquals("u_up[2] mismatch at step $k", refUUp[k][2], uUp[2], 1e-5)
            }

            val yawRate = DeviceOrientationCalibrator.extractVehicleYawRate(gyroK, gK)
            assertEquals("Yaw rate mismatch at step $k", refYawRate[k], yawRate, 1e-5)

            val (afP, alP, _) = calibrator.projectVehicleBodyAccel(accK, gK)
            assertEquals("af_proj mismatch at step $k", refAfProj[k], afP, 1e-4)
            assertEquals("al_proj mismatch at step $k", refAlProj[k], alP, 1e-4)
        }
    }

    @Test
    fun `numerical cross check ESKF fusion against python reference on real IO-VNBD segment`() {
        val t = extractDoubleArray(jsonString, "t")
        val af = extractDoubleArray(jsonString, "af")
        val al = extractDoubleArray(jsonString, "al")
        val gz = extractDoubleArray(jsonString, "gz")
        val gpsX = extractDoubleArray(jsonString, "gps_x")
        val gpsY = extractDoubleArray(jsonString, "gps_y")
        val gpsSpeed = extractDoubleArray(jsonString, "gps_speed")
        val gpsAccuracy = extractDoubleArray(jsonString, "gps_accuracy")
        val gpsSats = extractIntArray(jsonString, "gps_sats")
        val gpsFresh = extractBooleanArray(jsonString, "gps_fresh")
        val fixAge = extractDoubleArray(jsonString, "fix_age")

        val v0 = extractDouble(jsonString, "v0")
        val psi0 = extractDouble(jsonString, "psi0")
        val x0 = extractDouble(jsonString, "x0")
        val y0 = extractDouble(jsonString, "y0")

        val refX = extractDoubleArray(jsonString, "x")
        val refY = extractDoubleArray(jsonString, "y")
        val refVf = extractDoubleArray(jsonString, "vf")
        val refVl = extractDoubleArray(jsonString, "vl")
        val refPsi = extractDoubleArray(jsonString, "psi")
        val refGyroBias = extractDoubleArray(jsonString, "gyro_bias")

        val eskf = ESKFFusion(dt = 0.10)
        val out = eskf.filterBatch(
            t = t,
            af = af,
            al = al,
            gyroZ = gz,
            gpsX = gpsX,
            gpsY = gpsY,
            gpsSpeed = gpsSpeed,
            gpsAccuracy = gpsAccuracy,
            gpsSats = gpsSats,
            gpsFresh = gpsFresh,
            fixAge = fixAge,
            v0 = v0,
            psi0 = psi0,
            x0 = x0,
            y0 = y0,
        )

        val n = t.size
        for (k in 0 until n) {
            assertEquals("x mismatch at step $k", refX[k], out.x[k], 1e-4)
            assertEquals("y mismatch at step $k", refY[k], out.y[k], 1e-4)
            assertEquals("vf mismatch at step $k", refVf[k], out.vf[k], 1e-4)
            assertEquals("vl mismatch at step $k", refVl[k], out.vl[k], 1e-4)
            assertEquals("psi mismatch at step $k", refPsi[k], out.psi[k], 1e-4)
            assertEquals("gyro_bias mismatch at step $k", refGyroBias[k], out.gyroBias[k], 1e-5)
        }
    }
}
